sudo: required

dist: trusty

language: cpp

compiler:
  - g++
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email: false

sudo: false

script:
  - cd build/Linux
  - make
  - cd ../Windows
  - xbuild /p:Configuration=Release WorldCube.sln